[package]
name = "twobit-website"
version = "1.0.2"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.18"
tokio = { version = "1.5.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["fs"] }
